// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/sqnsl.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatabaseRequest) Reset() {
	*x = CreateDatabaseRequest{}
	mi := &file_api_proto_sqnsl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatabaseRequest) ProtoMessage() {}

func (x *CreateDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqnsl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatabaseRequest.ProtoReflect.Descriptor instead.
func (*CreateDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sqnsl_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDatabaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatabaseResponse) Reset() {
	*x = CreateDatabaseResponse{}
	mi := &file_api_proto_sqnsl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatabaseResponse) ProtoMessage() {}

func (x *CreateDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqnsl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatabaseResponse.ProtoReflect.Descriptor instead.
func (*CreateDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sqnsl_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDatabaseResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDatabaseResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListDatabasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatabasesRequest) Reset() {
	*x = ListDatabasesRequest{}
	mi := &file_api_proto_sqnsl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatabasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabasesRequest) ProtoMessage() {}

func (x *ListDatabasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqnsl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabasesRequest.ProtoReflect.Descriptor instead.
func (*ListDatabasesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sqnsl_proto_rawDescGZIP(), []int{2}
}

type DatabaseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	TableCount    int64                  `protobuf:"varint,5,opt,name=table_count,json=tableCount,proto3" json:"table_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseInfo) Reset() {
	*x = DatabaseInfo{}
	mi := &file_api_proto_sqnsl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseInfo) ProtoMessage() {}

func (x *DatabaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqnsl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseInfo.ProtoReflect.Descriptor instead.
func (*DatabaseInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_sqnsl_proto_rawDescGZIP(), []int{3}
}

func (x *DatabaseInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DatabaseInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DatabaseInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *DatabaseInfo) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *DatabaseInfo) GetTableCount() int64 {
	if x != nil {
		return x.TableCount
	}
	return 0
}

type ListDatabasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Databases     []*DatabaseInfo        `protobuf:"bytes,1,rep,name=databases,proto3" json:"databases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatabasesResponse) Reset() {
	*x = ListDatabasesResponse{}
	mi := &file_api_proto_sqnsl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatabasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabasesResponse) ProtoMessage() {}

func (x *ListDatabasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqnsl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabasesResponse.ProtoReflect.Descriptor instead.
func (*ListDatabasesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sqnsl_proto_rawDescGZIP(), []int{4}
}

func (x *ListDatabasesResponse) GetDatabases() []*DatabaseInfo {
	if x != nil {
		return x.Databases
	}
	return nil
}

type DropDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropDatabaseRequest) Reset() {
	*x = DropDatabaseRequest{}
	mi := &file_api_proto_sqnsl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropDatabaseRequest) ProtoMessage() {}

func (x *DropDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqnsl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropDatabaseRequest.ProtoReflect.Descriptor instead.
func (*DropDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sqnsl_proto_rawDescGZIP(), []int{5}
}

func (x *DropDatabaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DropDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropDatabaseResponse) Reset() {
	*x = DropDatabaseResponse{}
	mi := &file_api_proto_sqnsl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropDatabaseResponse) ProtoMessage() {}

func (x *DropDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqnsl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropDatabaseResponse.ProtoReflect.Descriptor instead.
func (*DropDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sqnsl_proto_rawDescGZIP(), []int{6}
}

func (x *DropDatabaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetDatabaseInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatabaseInfoRequest) Reset() {
	*x = GetDatabaseInfoRequest{}
	mi := &file_api_proto_sqnsl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseInfoRequest) ProtoMessage() {}

func (x *GetDatabaseInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqnsl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatabaseInfoRequest.ProtoReflect.Descriptor instead.
func (*GetDatabaseInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sqnsl_proto_rawDescGZIP(), []int{7}
}

func (x *GetDatabaseInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetDatabaseInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *DatabaseInfo          `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatabaseInfoResponse) Reset() {
	*x = GetDatabaseInfoResponse{}
	mi := &file_api_proto_sqnsl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseInfoResponse) ProtoMessage() {}

func (x *GetDatabaseInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqnsl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatabaseInfoResponse.ProtoReflect.Descriptor instead.
func (*GetDatabaseInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sqnsl_proto_rawDescGZIP(), []int{8}
}

func (x *GetDatabaseInfoResponse) GetDatabase() *DatabaseInfo {
	if x != nil {
		return x.Database
	}
	return nil
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	Params        []string               `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_api_proto_sqnsl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqnsl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sqnsl_proto_rawDescGZIP(), []int{9}
}

func (x *ExecuteRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *ExecuteRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *ExecuteRequest) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowsAffected  int64                  `protobuf:"varint,1,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	LastInsertId  int64                  `protobuf:"varint,2,opt,name=last_insert_id,json=lastInsertId,proto3" json:"last_insert_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_api_proto_sqnsl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqnsl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sqnsl_proto_rawDescGZIP(), []int{10}
}

func (x *ExecuteResponse) GetRowsAffected() int64 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

func (x *ExecuteResponse) GetLastInsertId() int64 {
	if x != nil {
		return x.LastInsertId
	}
	return 0
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	Params        []string               `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_api_proto_sqnsl_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqnsl_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sqnsl_proto_rawDescGZIP(), []int{11}
}

func (x *QueryRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *QueryRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *QueryRequest) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *QueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Column struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_api_proto_sqnsl_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqnsl_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_api_proto_sqnsl_proto_rawDescGZIP(), []int{12}
}

func (x *Column) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Column) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_api_proto_sqnsl_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqnsl_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_api_proto_sqnsl_proto_rawDescGZIP(), []int{13}
}

func (x *Row) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []*Column              `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	TotalCount    int64                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_api_proto_sqnsl_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqnsl_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sqnsl_proto_rawDescGZIP(), []int{14}
}

func (x *QueryResponse) GetColumns() []*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *QueryResponse) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *QueryResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type TableInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Columns       []*ColumnInfo          `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	Indexes       []*IndexInfo           `protobuf:"bytes,3,rep,name=indexes,proto3" json:"indexes,omitempty"`
	RowCount      int64                  `protobuf:"varint,4,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableInfo) Reset() {
	*x = TableInfo{}
	mi := &file_api_proto_sqnsl_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableInfo) ProtoMessage() {}

func (x *TableInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqnsl_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableInfo.ProtoReflect.Descriptor instead.
func (*TableInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_sqnsl_proto_rawDescGZIP(), []int{15}
}

func (x *TableInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableInfo) GetColumns() []*ColumnInfo {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *TableInfo) GetIndexes() []*IndexInfo {
	if x != nil {
		return x.Indexes
	}
	return nil
}

func (x *TableInfo) GetRowCount() int64 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

type ColumnInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Nullable      bool                   `protobuf:"varint,3,opt,name=nullable,proto3" json:"nullable,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	PrimaryKey    bool                   `protobuf:"varint,5,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnInfo) Reset() {
	*x = ColumnInfo{}
	mi := &file_api_proto_sqnsl_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnInfo) ProtoMessage() {}

func (x *ColumnInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqnsl_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnInfo.ProtoReflect.Descriptor instead.
func (*ColumnInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_sqnsl_proto_rawDescGZIP(), []int{16}
}

func (x *ColumnInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ColumnInfo) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *ColumnInfo) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *ColumnInfo) GetPrimaryKey() bool {
	if x != nil {
		return x.PrimaryKey
	}
	return false
}

type IndexInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Columns       []string               `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	Unique        bool                   `protobuf:"varint,3,opt,name=unique,proto3" json:"unique,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexInfo) Reset() {
	*x = IndexInfo{}
	mi := &file_api_proto_sqnsl_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexInfo) ProtoMessage() {}

func (x *IndexInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqnsl_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexInfo.ProtoReflect.Descriptor instead.
func (*IndexInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_sqnsl_proto_rawDescGZIP(), []int{17}
}

func (x *IndexInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IndexInfo) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *IndexInfo) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

type GetSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	mi := &file_api_proto_sqnsl_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqnsl_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sqnsl_proto_rawDescGZIP(), []int{18}
}

func (x *GetSchemaRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

type GetSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tables        []*TableInfo           `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_api_proto_sqnsl_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqnsl_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sqnsl_proto_rawDescGZIP(), []int{19}
}

func (x *GetSchemaResponse) GetTables() []*TableInfo {
	if x != nil {
		return x.Tables
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_api_proto_sqnsl_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqnsl_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sqnsl_proto_rawDescGZIP(), []int{20}
}

type PingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds   int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ActiveDatabases int32                  `protobuf:"varint,3,opt,name=active_databases,json=activeDatabases,proto3" json:"active_databases,omitempty"`
	MemoryBytes     int64                  `protobuf:"varint,4,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_api_proto_sqnsl_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqnsl_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sqnsl_proto_rawDescGZIP(), []int{21}
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *PingResponse) GetActiveDatabases() int32 {
	if x != nil {
		return x.ActiveDatabases
	}
	return 0
}

func (x *PingResponse) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

var File_api_proto_sqnsl_proto protoreflect.FileDescriptor

const file_api_proto_sqnsl_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/sqnsl.proto\x12\bsqnsl.v1\"+\n" +
	"\x15CreateDatabaseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"@\n" +
	"\x16CreateDatabaseResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x16\n" +
	"\x14ListDatabasesRequest\"\x8e\x01\n" +
	"\fDatabaseInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\x12\x1f\n" +
	"\vtable_count\x18\x05 \x01(\x03R\n" +
	"tableCount\"M\n" +
	"\x15ListDatabasesResponse\x124\n" +
	"\tdatabases\x18\x01 \x03(\v2\x16.sqnsl.v1.DatabaseInfoR\tdatabases\")\n" +
	"\x13DropDatabaseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"0\n" +
	"\x14DropDatabaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x16GetDatabaseInfoRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"M\n" +
	"\x17GetDatabaseInfoResponse\x122\n" +
	"\bdatabase\x18\x01 \x01(\v2\x16.sqnsl.v1.DatabaseInfoR\bdatabase\"V\n" +
	"\x0eExecuteRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\x12\x16\n" +
	"\x06params\x18\x03 \x03(\tR\x06params\"\\\n" +
	"\x0fExecuteResponse\x12#\n" +
	"\rrows_affected\x18\x01 \x01(\x03R\frowsAffected\x12$\n" +
	"\x0elast_insert_id\x18\x02 \x01(\x03R\flastInsertId\"\x82\x01\n" +
	"\fQueryRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\x12\x16\n" +
	"\x06params\x18\x03 \x03(\tR\x06params\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"0\n" +
	"\x06Column\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\x1d\n" +
	"\x03Row\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\x7f\n" +
	"\rQueryResponse\x12*\n" +
	"\acolumns\x18\x01 \x03(\v2\x10.sqnsl.v1.ColumnR\acolumns\x12!\n" +
	"\x04rows\x18\x02 \x03(\v2\r.sqnsl.v1.RowR\x04rows\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount\"\x9b\x01\n" +
	"\tTableInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\acolumns\x18\x02 \x03(\v2\x14.sqnsl.v1.ColumnInfoR\acolumns\x12-\n" +
	"\aindexes\x18\x03 \x03(\v2\x13.sqnsl.v1.IndexInfoR\aindexes\x12\x1b\n" +
	"\trow_count\x18\x04 \x01(\x03R\browCount\"\x96\x01\n" +
	"\n" +
	"ColumnInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bnullable\x18\x03 \x01(\bR\bnullable\x12#\n" +
	"\rdefault_value\x18\x04 \x01(\tR\fdefaultValue\x12\x1f\n" +
	"\vprimary_key\x18\x05 \x01(\bR\n" +
	"primaryKey\"Q\n" +
	"\tIndexInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acolumns\x18\x02 \x03(\tR\acolumns\x12\x16\n" +
	"\x06unique\x18\x03 \x01(\bR\x06unique\".\n" +
	"\x10GetSchemaRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\"@\n" +
	"\x11GetSchemaResponse\x12+\n" +
	"\x06tables\x18\x01 \x03(\v2\x13.sqnsl.v1.TableInfoR\x06tables\"\r\n" +
	"\vPingRequest\"\x9d\x01\n" +
	"\fPingResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12)\n" +
	"\x10active_databases\x18\x03 \x01(\x05R\x0factiveDatabases\x12!\n" +
	"\fmemory_bytes\x18\x04 \x01(\x03R\vmemoryBytes2\xd3\x04\n" +
	"\fSqlNotSoLite\x12S\n" +
	"\x0eCreateDatabase\x12\x1f.sqnsl.v1.CreateDatabaseRequest\x1a .sqnsl.v1.CreateDatabaseResponse\x12P\n" +
	"\rListDatabases\x12\x1e.sqnsl.v1.ListDatabasesRequest\x1a\x1f.sqnsl.v1.ListDatabasesResponse\x12M\n" +
	"\fDropDatabase\x12\x1d.sqnsl.v1.DropDatabaseRequest\x1a\x1e.sqnsl.v1.DropDatabaseResponse\x12V\n" +
	"\x0fGetDatabaseInfo\x12 .sqnsl.v1.GetDatabaseInfoRequest\x1a!.sqnsl.v1.GetDatabaseInfoResponse\x12>\n" +
	"\aExecute\x12\x18.sqnsl.v1.ExecuteRequest\x1a\x19.sqnsl.v1.ExecuteResponse\x128\n" +
	"\x05Query\x12\x16.sqnsl.v1.QueryRequest\x1a\x17.sqnsl.v1.QueryResponse\x12D\n" +
	"\tGetSchema\x12\x1a.sqnsl.v1.GetSchemaRequest\x1a\x1b.sqnsl.v1.GetSchemaResponse\x125\n" +
	"\x04Ping\x12\x15.sqnsl.v1.PingRequest\x1a\x16.sqnsl.v1.PingResponseB2Z0github.com/mbianchidev/sql-not-so-lite/api/protob\x06proto3"

var (
	file_api_proto_sqnsl_proto_rawDescOnce sync.Once
	file_api_proto_sqnsl_proto_rawDescData []byte
)

func file_api_proto_sqnsl_proto_rawDescGZIP() []byte {
	file_api_proto_sqnsl_proto_rawDescOnce.Do(func() {
		file_api_proto_sqnsl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_sqnsl_proto_rawDesc), len(file_api_proto_sqnsl_proto_rawDesc)))
	})
	return file_api_proto_sqnsl_proto_rawDescData
}

var file_api_proto_sqnsl_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_proto_sqnsl_proto_goTypes = []any{
	(*CreateDatabaseRequest)(nil),   // 0: sqnsl.v1.CreateDatabaseRequest
	(*CreateDatabaseResponse)(nil),  // 1: sqnsl.v1.CreateDatabaseResponse
	(*ListDatabasesRequest)(nil),    // 2: sqnsl.v1.ListDatabasesRequest
	(*DatabaseInfo)(nil),            // 3: sqnsl.v1.DatabaseInfo
	(*ListDatabasesResponse)(nil),   // 4: sqnsl.v1.ListDatabasesResponse
	(*DropDatabaseRequest)(nil),     // 5: sqnsl.v1.DropDatabaseRequest
	(*DropDatabaseResponse)(nil),    // 6: sqnsl.v1.DropDatabaseResponse
	(*GetDatabaseInfoRequest)(nil),  // 7: sqnsl.v1.GetDatabaseInfoRequest
	(*GetDatabaseInfoResponse)(nil), // 8: sqnsl.v1.GetDatabaseInfoResponse
	(*ExecuteRequest)(nil),          // 9: sqnsl.v1.ExecuteRequest
	(*ExecuteResponse)(nil),         // 10: sqnsl.v1.ExecuteResponse
	(*QueryRequest)(nil),            // 11: sqnsl.v1.QueryRequest
	(*Column)(nil),                  // 12: sqnsl.v1.Column
	(*Row)(nil),                     // 13: sqnsl.v1.Row
	(*QueryResponse)(nil),           // 14: sqnsl.v1.QueryResponse
	(*TableInfo)(nil),               // 15: sqnsl.v1.TableInfo
	(*ColumnInfo)(nil),              // 16: sqnsl.v1.ColumnInfo
	(*IndexInfo)(nil),               // 17: sqnsl.v1.IndexInfo
	(*GetSchemaRequest)(nil),        // 18: sqnsl.v1.GetSchemaRequest
	(*GetSchemaResponse)(nil),       // 19: sqnsl.v1.GetSchemaResponse
	(*PingRequest)(nil),             // 20: sqnsl.v1.PingRequest
	(*PingResponse)(nil),            // 21: sqnsl.v1.PingResponse
}
var file_api_proto_sqnsl_proto_depIdxs = []int32{
	3,  // 0: sqnsl.v1.ListDatabasesResponse.databases:type_name -> sqnsl.v1.DatabaseInfo
	3,  // 1: sqnsl.v1.GetDatabaseInfoResponse.database:type_name -> sqnsl.v1.DatabaseInfo
	12, // 2: sqnsl.v1.QueryResponse.columns:type_name -> sqnsl.v1.Column
	13, // 3: sqnsl.v1.QueryResponse.rows:type_name -> sqnsl.v1.Row
	16, // 4: sqnsl.v1.TableInfo.columns:type_name -> sqnsl.v1.ColumnInfo
	17, // 5: sqnsl.v1.TableInfo.indexes:type_name -> sqnsl.v1.IndexInfo
	15, // 6: sqnsl.v1.GetSchemaResponse.tables:type_name -> sqnsl.v1.TableInfo
	0,  // 7: sqnsl.v1.SqlNotSoLite.CreateDatabase:input_type -> sqnsl.v1.CreateDatabaseRequest
	2,  // 8: sqnsl.v1.SqlNotSoLite.ListDatabases:input_type -> sqnsl.v1.ListDatabasesRequest
	5,  // 9: sqnsl.v1.SqlNotSoLite.DropDatabase:input_type -> sqnsl.v1.DropDatabaseRequest
	7,  // 10: sqnsl.v1.SqlNotSoLite.GetDatabaseInfo:input_type -> sqnsl.v1.GetDatabaseInfoRequest
	9,  // 11: sqnsl.v1.SqlNotSoLite.Execute:input_type -> sqnsl.v1.ExecuteRequest
	11, // 12: sqnsl.v1.SqlNotSoLite.Query:input_type -> sqnsl.v1.QueryRequest
	18, // 13: sqnsl.v1.SqlNotSoLite.GetSchema:input_type -> sqnsl.v1.GetSchemaRequest
	20, // 14: sqnsl.v1.SqlNotSoLite.Ping:input_type -> sqnsl.v1.PingRequest
	1,  // 15: sqnsl.v1.SqlNotSoLite.CreateDatabase:output_type -> sqnsl.v1.CreateDatabaseResponse
	4,  // 16: sqnsl.v1.SqlNotSoLite.ListDatabases:output_type -> sqnsl.v1.ListDatabasesResponse
	6,  // 17: sqnsl.v1.SqlNotSoLite.DropDatabase:output_type -> sqnsl.v1.DropDatabaseResponse
	8,  // 18: sqnsl.v1.SqlNotSoLite.GetDatabaseInfo:output_type -> sqnsl.v1.GetDatabaseInfoResponse
	10, // 19: sqnsl.v1.SqlNotSoLite.Execute:output_type -> sqnsl.v1.ExecuteResponse
	14, // 20: sqnsl.v1.SqlNotSoLite.Query:output_type -> sqnsl.v1.QueryResponse
	19, // 21: sqnsl.v1.SqlNotSoLite.GetSchema:output_type -> sqnsl.v1.GetSchemaResponse
	21, // 22: sqnsl.v1.SqlNotSoLite.Ping:output_type -> sqnsl.v1.PingResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_sqnsl_proto_init() }
func file_api_proto_sqnsl_proto_init() {
	if File_api_proto_sqnsl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_sqnsl_proto_rawDesc), len(file_api_proto_sqnsl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_sqnsl_proto_goTypes,
		DependencyIndexes: file_api_proto_sqnsl_proto_depIdxs,
		MessageInfos:      file_api_proto_sqnsl_proto_msgTypes,
	}.Build()
	File_api_proto_sqnsl_proto = out.File
	file_api_proto_sqnsl_proto_goTypes = nil
	file_api_proto_sqnsl_proto_depIdxs = nil
}
